import { createElement } from 'lwc';
import Lwc_2310_eg1_event_program_grandparent from 'c/lwc_2310_eg1_event_program_grandparent';

describe('c-lwc-2310-eg1-event-program-grandparent', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-2310-eg1-event-program-grandparent', {
            is: Lwc_2310_eg1_event_program_grandparent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});