import { createElement } from 'lwc';
import Lwc_22_12_eg2_greter3Num from 'c/lwc_22_12_eg2_greter3Num';

describe('c-lwc-22-12-eg2-greter3-num', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-22-12-eg2-greter3-num', {
            is: Lwc_22_12_eg2_greter3Num
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});