import { createElement } from 'lwc';
import Lwc_1810_eg2_UpdateAcc_LWC_IMP from 'c/lwc_1810_eg2_UpdateAcc_LWC_IMP';

describe('c-lwc-1810-eg2-update-acc-l-w-c-imp', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-1810-eg2-update-acc-l-w-c-imp', {
            is: Lwc_1810_eg2_UpdateAcc_LWC_IMP
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});