import { createElement } from 'lwc';
import Lwc_2210_eg1_event_declarative_enter_emp_detail from 'c/lwc_2210_eg1_event_declarative_enter_emp_detail';

describe('c-lwc-2210-eg1-event-declarative-enter-emp-detail', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-2210-eg1-event-declarative-enter-emp-detail', {
            is: Lwc_2210_eg1_event_declarative_enter_emp_detail
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});