import { createElement } from 'lwc';
import Lwc_1710_eg3_Createacc_SSC_IMP from 'c/lwc_1710_eg3_Createacc_SSC_IMP';

describe('c-lwc-1710-eg3-createacc-s-s-c-imp', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-1710-eg3-createacc-s-s-c-imp', {
            is: Lwc_1710_eg3_Createacc_SSC_IMP
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});