import { createElement } from 'lwc';
import Lwc_0810_eg5_CollectionDatatype from 'c/lwc_0810_eg5_CollectionDatatype';

describe('c-lwc-0810-eg5-collection-datatype', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-0810-eg5-collection-datatype', {
            is: Lwc_0810_eg5_CollectionDatatype
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});