import { createElement } from 'lwc';
import Lwc_22_12_eg1_var_basics from 'c/lwc_22_12_eg1_var_basics';

describe('c-lwc-22-12-eg1-var-basics', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-22-12-eg1-var-basics', {
            is: Lwc_22_12_eg1_var_basics
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});